name: build docker image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_REPO: jonohill/plate-api

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Login to ghcr
        uses: docker/login-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get a user agent
        id: ua
        run: |
          ua() {
            curl -L --fail https://github.com/intoli/user-agents/raw/master/src/user-agents.json.gz | \
            gunzip -c - | \
            jq -r 'sort_by(.weight) | reverse | .[0] | .userAgent'
          }
          echo "::set-output name=user_agent::$(ua)"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          build_args: |
            PLATE_API_USER_AGENT="${{ steps.ua.outputs.user_agent }}"
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max          
          tags: "${{ env.DOCKER_REGISTRY}}/${{ env.DOCKER_REPO }}:${{ github.run_number }}"
